export const categories = [
  "Transporter",
  "Broker",
  "Fleet Owner",
  "Truck Owner",
  "Logistics Company",
  "Warehouse",
  "Courier",
  "Packing & Moving",
  "Commission Agent",
  "RTO Agent",
  "Finance Agent",
  "Other",
];

export const vehicleOptions = [
  "Mini Truck",
  "Pickup",
  "Tata Ace",
  "Bolero Pickup",
  "Mahindra Jeeto",
  "Ashok Leyland Dost",
  "Tempo",
  "Canter",
  "Eicher",
  "Truck",
  "LCV",
  "HCV",
  "14 Feet Truck",
  "17 Feet Truck",
  "19 Feet Truck",
  "22 Feet Truck",
  "32 Feet Truck",
  "Open Body Truck",
  "Closed Body Truck",
  "Container",
  "Trailer",
  "Tipper",
  "Tanker",
  "Refrigerated Truck",
  "Tractor Trolley",
];